name: dart_dev
version: 1.3.0
description: Centralized tooling for Dart projects. Consistent interface across projects. Easily configurable.
authors:
  - Workiva Client Platform Team <clientplatform@workiva.com>
  - Dustin Lessard <dustin.lessard@workiva.com>
  - Evan Weible <evan.weible@workiva.com>
  - Jay Udey <jay.udey@workiva.com>
  - Max Peterson <maxwell.peterson@workiva.com>
  - Trent Grover <trent.grover@workiva.com>
homepage: https://github.com/Workiva/dart_dev
dependencies:
  ansicolor: "^0.0.9"
  args: "^0.13.0"
  completion: "^0.1.5"
  coverage: "^0.7.3"
  dart_style: ">=0.2.4 <0.3.0"
  dartdoc: ">=0.4.0 <0.9.0"
  path: "^1.3.6"
  resource: "^1.1.0"
  test: "^0.12.0"
  uuid: "^0.5.0"
  yaml: "^2.1.0"
executables:
  dart_dev:
environment:
  sdk: ">=1.9.0 <2.0.0"
